### ISSUE TITLE
无法获得分词结果？

### ISSUE THREAD

**Issue by lcp580** [jaiminpan/pg_scws#1]
test=# select \* from to_tsvector('scwscfg', '李小福是创新办主任也是云计算方面的 专家');
##  to_tsvector
# (1 row)

没有分词的结果？？请教，是什么问题。

**Comment by jaiminpan** [comment]
Thanks for your report this.
It's fixed in latest commit. Please update your code then try again.

**Comment by lcp580** [comment]
thank you !very match
